# Generated by Django 5.2.6 on 2026-03-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_exercise',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_ladder',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_weekly_plan',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_session',
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LadderNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Tier in the tree (for display ordering)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_nodes', to='workout.exercise')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workout.ladder')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='workout.laddernode')),
            ],
            options={
                'db_table': 'workout_ladder_node',
                'ordering': ['ladder', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('min_reps_sets', 'Minimum reps & sets'), ('min_weight', 'Minimum weight'), ('sustained_sessions', 'Sustained over sessions'), ('min_duration', 'Minimum duration')], max_length=50)),
                ('params', models.JSONField(help_text='Shape determined by type, e.g. {"sets": 3, "reps": 10}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ladder_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='workout.laddernode')),
            ],
            options={
                'verbose_name_plural': 'criteria',
                'db_table': 'workout_criterion',
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='workout.exercise')),
                ('ladder_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_exercises', to='workout.laddernode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workoutsession')),
            ],
            options={
                'db_table': 'workout_session_exercise',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('reps_weight', 'Reps & Weight'), ('reps_only', 'Reps Only'), ('duration', 'Duration'), ('distance', 'Distance')], max_length=30)),
                ('value', models.JSONField(help_text='Shape determined by type, e.g. {"reps": 10, "weight": 20}')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.sessionexercise')),
            ],
            options={
                'db_table': 'workout_exercise_set',
                'ordering': ['session_exercise', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('order', models.PositiveIntegerField()),
                ('exercise_params', models.JSONField(blank=True, help_text='Typed params, e.g. {"type": "reps_weight", "sets": 4, "reps": 8, "weight": 20}', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_slots', to='workout.exercise')),
                ('ladder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_slots', to='workout.ladder')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workout.weeklyplan')),
            ],
            options={
                'db_table': 'workout_plan_slot',
                'ordering': ['weekly_plan', 'day_of_week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_user',
            },
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workout.workoutuser'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='workout.workoutuser'),
        ),
        migrations.AddField(
            model_name='ladder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladders', to='workout.workoutuser'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workoutuser'),
        ),
        migrations.CreateModel(
            name='UserNodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ladder_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='workout.laddernode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to='workout.workoutuser')),
            ],
            options={
                'db_table': 'workout_user_node_progress',
                'unique_together': {('user', 'ladder_node')},
            },
        ),
    ]
