# Generated by Django 5.2.12 on 2026-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'workout_muscle_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='is_warmup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='warmup_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='workout.musclegroup'),
        ),
        migrations.CreateModel(
            name='WarmUpExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('muscle_groups', models.ManyToManyField(related_name='warmup_exercises', to='workout.musclegroup')),
            ],
            options={
                'db_table': 'workout_warmup_exercise',
                'ordering': ['name'],
            },
        ),
    ]
