# Generated by Django 5.2.12 on 2026-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_musclegroup_sessionexercise_is_warmup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='is_warmup_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laddernode',
            name='warmup_sets_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of warm-up sets before working sets (0 = none)'),
        ),
        migrations.AddField(
            model_name='laddernode',
            name='warmup_start_pct',
            field=models.PositiveIntegerField(default=20, help_text='Starting weight percentage for warm-up sets (e.g. 20 = 20%)'),
        ),
        migrations.AddField(
            model_name='usernodeprogress',
            name='working_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Current working weight in kg. Set during onboarding, updated after sessions.', max_digits=6, null=True),
        ),
    ]
